{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bravepipeproject",
    "module": "extractor",
    "version": "v0.24.8-2.3.3-test9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "4.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "extractor-v0.24.8-2.3.3-test9.jar",
          "url": "extractor-v0.24.8-2.3.3-test9.jar",
          "size": 972398,
          "sha512": "ca90a50325180418a53d81298f601c7909df28e7983d1c6f633a5adce2147a60815ee82e067d02bacded3397c54fc462c7146267eab16fe184e4a6166cdb0360",
          "sha256": "d766156f0cc0824c6efa78c8245d2f63cf78fb0bf8505829e20398889c2ca212",
          "sha1": "52e7880fdc265ad8826f410e45fddce7b7a35435",
          "md5": "a7777b824dd725548a062fc55d22df08"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bravepipeproject",
          "module": "timeago-parser",
          "version": {
            "requires": "v0.24.8-2.3.3-test9"
          }
        },
        {
          "group": "com.github.TeamNewPipe",
          "module": "nanojson",
          "version": {
            "requires": "e9d656ddb49a412a5a0a5d5ef20ca7ef09549996"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.31.1"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino-engine",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.github.evermind-zz",
          "module": "hlsdownloader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "4.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "extractor-v0.24.8-2.3.3-test9.jar",
          "url": "extractor-v0.24.8-2.3.3-test9.jar",
          "size": 972398,
          "sha512": "ca90a50325180418a53d81298f601c7909df28e7983d1c6f633a5adce2147a60815ee82e067d02bacded3397c54fc462c7146267eab16fe184e4a6166cdb0360",
          "sha256": "d766156f0cc0824c6efa78c8245d2f63cf78fb0bf8505829e20398889c2ca212",
          "sha1": "52e7880fdc265ad8826f410e45fddce7b7a35435",
          "md5": "a7777b824dd725548a062fc55d22df08"
        }
      ]
    }
  ]
}
