{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bravepipeproject",
    "module": "extractor",
    "version": "v0.24.8-2.3.3-test4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "4.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "extractor-v0.24.8-2.3.3-test4.jar",
          "url": "extractor-v0.24.8-2.3.3-test4.jar",
          "size": 972398,
          "sha512": "1208fbff9f758890af2edd4aa4ed676e49f3701b6cfe47624fefc8c1af74cce0194e6ab5d82cb6a81f3ef887b55b9958f31b65c42b6b8506f30915c951369140",
          "sha256": "c4e9ab6e822894908a12976be3ffdfdd00b4c8b4e0f947ac91785242398306be",
          "sha1": "96e174bd7ad6c6a3aa1f2bf5e3a724c81f35a9af",
          "md5": "3f19bed2d03e0d3c180ec331dcefa9e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bravepipeproject",
          "module": "timeago-parser",
          "version": {
            "requires": "v0.24.8-2.3.3-test4"
          }
        },
        {
          "group": "com.github.TeamNewPipe",
          "module": "nanojson",
          "version": {
            "requires": "e9d656ddb49a412a5a0a5d5ef20ca7ef09549996"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.31.1"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino-engine",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.github.evermind-zz",
          "module": "hlsdownloader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "4.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "extractor-v0.24.8-2.3.3-test4.jar",
          "url": "extractor-v0.24.8-2.3.3-test4.jar",
          "size": 972398,
          "sha512": "1208fbff9f758890af2edd4aa4ed676e49f3701b6cfe47624fefc8c1af74cce0194e6ab5d82cb6a81f3ef887b55b9958f31b65c42b6b8506f30915c951369140",
          "sha256": "c4e9ab6e822894908a12976be3ffdfdd00b4c8b4e0f947ac91785242398306be",
          "sha1": "96e174bd7ad6c6a3aa1f2bf5e3a724c81f35a9af",
          "md5": "3f19bed2d03e0d3c180ec331dcefa9e4"
        }
      ]
    }
  ]
}
