{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bravepipeproject",
    "module": "timeago-generator",
    "version": "v0.24.8-2.3.3-test9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "timeago-generator-v0.24.8-2.3.3-test9.jar",
          "url": "timeago-generator-v0.24.8-2.3.3-test9.jar",
          "size": 13140,
          "sha512": "5f5803cb2413766a8f5dfb1f4f517ee0c3ee5f002458b12df576a76d5080733af2dc566eee4f0fa8b41385bf678f9751f939b006da2f5c9bbc9bff4b624ae4b7",
          "sha256": "1da7c891cd7cc0a3d164b815f8134d046d4803ea7bd138e1b6543fb4dfd756a9",
          "sha1": "0f20970f5a24924cb1bb2e6c1d1ab3ec830e2809",
          "md5": "31e85365bc24446a33a47ff66330c6f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.TeamNewPipe",
          "module": "nanojson",
          "version": {
            "requires": "e9d656ddb49a412a5a0a5d5ef20ca7ef09549996"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.github.bravepipeproject",
          "module": "timeago-parser",
          "version": {
            "requires": "v0.24.8-2.3.3-test9"
          }
        }
      ],
      "files": [
        {
          "name": "timeago-generator-v0.24.8-2.3.3-test9.jar",
          "url": "timeago-generator-v0.24.8-2.3.3-test9.jar",
          "size": 13140,
          "sha512": "5f5803cb2413766a8f5dfb1f4f517ee0c3ee5f002458b12df576a76d5080733af2dc566eee4f0fa8b41385bf678f9751f939b006da2f5c9bbc9bff4b624ae4b7",
          "sha256": "1da7c891cd7cc0a3d164b815f8134d046d4803ea7bd138e1b6543fb4dfd756a9",
          "sha1": "0f20970f5a24924cb1bb2e6c1d1ab3ec830e2809",
          "md5": "31e85365bc24446a33a47ff66330c6f1"
        }
      ]
    }
  ]
}
