{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bravepipeproject",
    "module": "extractor",
    "version": "v0.24.8-2.3.3-test8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "4.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "extractor-v0.24.8-2.3.3-test8.jar",
          "url": "extractor-v0.24.8-2.3.3-test8.jar",
          "size": 972398,
          "sha512": "1100faee8bba42d7c124a96f7cffb43167d24ddf7fb2c4827833e74b9cc38396d0290ca59e41c00d8b46ebdecfbe2be5d530a8ac0fd1190997f7b54565eda9a7",
          "sha256": "f205390d24e659db54a2ceef2cdfcc859d4709e5a617cda9f9e7d26011f3844c",
          "sha1": "ec96c3b952df4f22a9b1cf60fd8ecbedf7f62f54",
          "md5": "fdc3ce673c60a7cf433c2626346fc72f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bravepipeproject",
          "module": "timeago-parser",
          "version": {
            "requires": "v0.24.8-2.3.3-test8"
          }
        },
        {
          "group": "com.github.TeamNewPipe",
          "module": "nanojson",
          "version": {
            "requires": "e9d656ddb49a412a5a0a5d5ef20ca7ef09549996"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.31.1"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino-engine",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.github.evermind-zz",
          "module": "hlsdownloader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "4.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "extractor-v0.24.8-2.3.3-test8.jar",
          "url": "extractor-v0.24.8-2.3.3-test8.jar",
          "size": 972398,
          "sha512": "1100faee8bba42d7c124a96f7cffb43167d24ddf7fb2c4827833e74b9cc38396d0290ca59e41c00d8b46ebdecfbe2be5d530a8ac0fd1190997f7b54565eda9a7",
          "sha256": "f205390d24e659db54a2ceef2cdfcc859d4709e5a617cda9f9e7d26011f3844c",
          "sha1": "ec96c3b952df4f22a9b1cf60fd8ecbedf7f62f54",
          "md5": "fdc3ce673c60a7cf433c2626346fc72f"
        }
      ]
    }
  ]
}
