{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bravepipeproject",
    "module": "timeago-generator",
    "version": "v0.24.8-2.3.3-test3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "timeago-generator-v0.24.8-2.3.3-test3.jar",
          "url": "timeago-generator-v0.24.8-2.3.3-test3.jar",
          "size": 13140,
          "sha512": "9301add6eea4b0afe1c98d0e83c641bc17fd03331744d4a729b7d8d373edbd9bc46a7e1a211736b302d95ecbb8a4575b7298488f0f79ecbab58304cc9752187d",
          "sha256": "3023ac131ef51038ced11b9f6287687dd02143d36e806383b498a33dd7a7349f",
          "sha1": "81eb5f9d0962e24ce390cf0b15465b003d87f6b6",
          "md5": "9cfadfdd3bfff8ab662ed3c9a4e9f2d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.TeamNewPipe",
          "module": "nanojson",
          "version": {
            "requires": "e9d656ddb49a412a5a0a5d5ef20ca7ef09549996"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.github.bravepipeproject",
          "module": "timeago-parser",
          "version": {
            "requires": "v0.24.8-2.3.3-test3"
          }
        }
      ],
      "files": [
        {
          "name": "timeago-generator-v0.24.8-2.3.3-test3.jar",
          "url": "timeago-generator-v0.24.8-2.3.3-test3.jar",
          "size": 13140,
          "sha512": "9301add6eea4b0afe1c98d0e83c641bc17fd03331744d4a729b7d8d373edbd9bc46a7e1a211736b302d95ecbb8a4575b7298488f0f79ecbab58304cc9752187d",
          "sha256": "3023ac131ef51038ced11b9f6287687dd02143d36e806383b498a33dd7a7349f",
          "sha1": "81eb5f9d0962e24ce390cf0b15465b003d87f6b6",
          "md5": "9cfadfdd3bfff8ab662ed3c9a4e9f2d4"
        }
      ]
    }
  ]
}
