{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bravepipeproject",
    "module": "extractor",
    "version": "v0.24.8-2.3.3-test2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "4.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "extractor-v0.24.8-2.3.3-test2.jar",
          "url": "extractor-v0.24.8-2.3.3-test2.jar",
          "size": 972398,
          "sha512": "b2f498b7c3ba382cc5844677a4b506cd496a37d40bf182ef27e16872c2172e9705fc0a6106b0697933fead9bb7f2364c19ce6d86b88bcf6399dceabd8bd63a5d",
          "sha256": "d7a2a3de201e8c07fc8721fab76e22e72d0b5961438345679d9c72a8ba0c3582",
          "sha1": "3a0c3dda01a16837eb44e53838e9175e9a287737",
          "md5": "82bb02d41dfe4a69ee16d9f4eb4435b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bravepipeproject",
          "module": "timeago-parser",
          "version": {
            "requires": "v0.24.8-2.3.3-test2"
          }
        },
        {
          "group": "com.github.TeamNewPipe",
          "module": "nanojson",
          "version": {
            "requires": "e9d656ddb49a412a5a0a5d5ef20ca7ef09549996"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.31.1"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino-engine",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.github.evermind-zz",
          "module": "hlsdownloader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "4.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "extractor-v0.24.8-2.3.3-test2.jar",
          "url": "extractor-v0.24.8-2.3.3-test2.jar",
          "size": 972398,
          "sha512": "b2f498b7c3ba382cc5844677a4b506cd496a37d40bf182ef27e16872c2172e9705fc0a6106b0697933fead9bb7f2364c19ce6d86b88bcf6399dceabd8bd63a5d",
          "sha256": "d7a2a3de201e8c07fc8721fab76e22e72d0b5961438345679d9c72a8ba0c3582",
          "sha1": "3a0c3dda01a16837eb44e53838e9175e9a287737",
          "md5": "82bb02d41dfe4a69ee16d9f4eb4435b2"
        }
      ]
    }
  ]
}
