{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bravepipeproject",
    "module": "timeago-generator",
    "version": "v0.24.8-2.3.3-test6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "timeago-generator-v0.24.8-2.3.3-test6.jar",
          "url": "timeago-generator-v0.24.8-2.3.3-test6.jar",
          "size": 13140,
          "sha512": "655d1970a4a32b5b2be1cf922ec2f827f1376925083a0308a35c9156253e8192aeda127164b1c59e860f58624846b66375ca557e31c2d19267149c44544c2051",
          "sha256": "addb26ecadc544a6ad1e23c397bf2b927259be0fce401208b71845f985f7b6a4",
          "sha1": "fe98fbd2c2b2439059292f6d7b49bd2bd648a29f",
          "md5": "ff59c04dddf454e6a024b26c2f719177"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.TeamNewPipe",
          "module": "nanojson",
          "version": {
            "requires": "e9d656ddb49a412a5a0a5d5ef20ca7ef09549996"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.github.bravepipeproject",
          "module": "timeago-parser",
          "version": {
            "requires": "v0.24.8-2.3.3-test6"
          }
        }
      ],
      "files": [
        {
          "name": "timeago-generator-v0.24.8-2.3.3-test6.jar",
          "url": "timeago-generator-v0.24.8-2.3.3-test6.jar",
          "size": 13140,
          "sha512": "655d1970a4a32b5b2be1cf922ec2f827f1376925083a0308a35c9156253e8192aeda127164b1c59e860f58624846b66375ca557e31c2d19267149c44544c2051",
          "sha256": "addb26ecadc544a6ad1e23c397bf2b927259be0fce401208b71845f985f7b6a4",
          "sha1": "fe98fbd2c2b2439059292f6d7b49bd2bd648a29f",
          "md5": "ff59c04dddf454e6a024b26c2f719177"
        }
      ]
    }
  ]
}
