{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bravepipeproject",
    "module": "timeago-generator",
    "version": "v0.24.8-2.3.3-test2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "timeago-generator-v0.24.8-2.3.3-test2.jar",
          "url": "timeago-generator-v0.24.8-2.3.3-test2.jar",
          "size": 13140,
          "sha512": "0c417f03a8a2a2cc0859fa9e05434df4779126126bf6a4c04b1b88d657a45c00ee673a299eface607ed30e598c4ba94e602d047a8d5503d65309a3c36fb6ab45",
          "sha256": "12c17eb0d61224711ba3109e6464e56fc43a8d7c3d49e0c28a1dd67401d431e2",
          "sha1": "d284e24569446833262b0e40e65b2c703ccab5d3",
          "md5": "0e9000dbdcb29aba8af4c22d96357e44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.TeamNewPipe",
          "module": "nanojson",
          "version": {
            "requires": "e9d656ddb49a412a5a0a5d5ef20ca7ef09549996"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.github.bravepipeproject",
          "module": "timeago-parser",
          "version": {
            "requires": "v0.24.8-2.3.3-test2"
          }
        }
      ],
      "files": [
        {
          "name": "timeago-generator-v0.24.8-2.3.3-test2.jar",
          "url": "timeago-generator-v0.24.8-2.3.3-test2.jar",
          "size": 13140,
          "sha512": "0c417f03a8a2a2cc0859fa9e05434df4779126126bf6a4c04b1b88d657a45c00ee673a299eface607ed30e598c4ba94e602d047a8d5503d65309a3c36fb6ab45",
          "sha256": "12c17eb0d61224711ba3109e6464e56fc43a8d7c3d49e0c28a1dd67401d431e2",
          "sha1": "d284e24569446833262b0e40e65b2c703ccab5d3",
          "md5": "0e9000dbdcb29aba8af4c22d96357e44"
        }
      ]
    }
  ]
}
