{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bravepipeproject",
    "module": "extractor",
    "version": "v0.24.8-2.3.3-test10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "4.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "extractor-v0.24.8-2.3.3-test10.jar",
          "url": "extractor-v0.24.8-2.3.3-test10.jar",
          "size": 972398,
          "sha512": "9d07ff0521f7f5a789e8f82f669c39b4ef147424d12476761fea3033b793099d238370d621ae93c3ae0298472478bdf9a4790e085860f06a81d3b4d8a9c37d57",
          "sha256": "89bf34f4f9222bc4f6f9da11b34f45d8e66842159ed6365bcc7c6848153b3b41",
          "sha1": "2b91ab6e01e5c8db44ec657c2fa81e7ede491b48",
          "md5": "c6dced7cf4da4335f91deee67b7cb5a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bravepipeproject",
          "module": "timeago-parser",
          "version": {
            "requires": "v0.24.8-2.3.3-test10"
          }
        },
        {
          "group": "com.github.TeamNewPipe",
          "module": "nanojson",
          "version": {
            "requires": "e9d656ddb49a412a5a0a5d5ef20ca7ef09549996"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.31.1"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino-engine",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.github.evermind-zz",
          "module": "hlsdownloader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "4.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "extractor-v0.24.8-2.3.3-test10.jar",
          "url": "extractor-v0.24.8-2.3.3-test10.jar",
          "size": 972398,
          "sha512": "9d07ff0521f7f5a789e8f82f669c39b4ef147424d12476761fea3033b793099d238370d621ae93c3ae0298472478bdf9a4790e085860f06a81d3b4d8a9c37d57",
          "sha256": "89bf34f4f9222bc4f6f9da11b34f45d8e66842159ed6365bcc7c6848153b3b41",
          "sha1": "2b91ab6e01e5c8db44ec657c2fa81e7ede491b48",
          "md5": "c6dced7cf4da4335f91deee67b7cb5a6"
        }
      ]
    }
  ]
}
