{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bravepipeproject",
    "module": "timeago-generator",
    "version": "v0.24.8-2.3.3-test5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "timeago-generator-v0.24.8-2.3.3-test5.jar",
          "url": "timeago-generator-v0.24.8-2.3.3-test5.jar",
          "size": 13140,
          "sha512": "344aaff4b8a6395f77dc9591d3510eefdb1361c69b8e127f07dbde728e88a068e08b098bf1847aca960446cb053f4ac9f9844469d627c1f4577b113c0f27c018",
          "sha256": "5ce43420cd1275c349c09dda061579c1ca0dc19267839d473c39d1a358f78ffc",
          "sha1": "984c48a1bab22e2b948656202c92bfff18647c8f",
          "md5": "32ab758bc1c3e54143c9f90572095ce2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.TeamNewPipe",
          "module": "nanojson",
          "version": {
            "requires": "e9d656ddb49a412a5a0a5d5ef20ca7ef09549996"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.github.bravepipeproject",
          "module": "timeago-parser",
          "version": {
            "requires": "v0.24.8-2.3.3-test5"
          }
        }
      ],
      "files": [
        {
          "name": "timeago-generator-v0.24.8-2.3.3-test5.jar",
          "url": "timeago-generator-v0.24.8-2.3.3-test5.jar",
          "size": 13140,
          "sha512": "344aaff4b8a6395f77dc9591d3510eefdb1361c69b8e127f07dbde728e88a068e08b098bf1847aca960446cb053f4ac9f9844469d627c1f4577b113c0f27c018",
          "sha256": "5ce43420cd1275c349c09dda061579c1ca0dc19267839d473c39d1a358f78ffc",
          "sha1": "984c48a1bab22e2b948656202c92bfff18647c8f",
          "md5": "32ab758bc1c3e54143c9f90572095ce2"
        }
      ]
    }
  ]
}
