{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bravepipeproject",
    "module": "extractor",
    "version": "v0.24.8-2.3.3-test5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "4.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "extractor-v0.24.8-2.3.3-test5.jar",
          "url": "extractor-v0.24.8-2.3.3-test5.jar",
          "size": 972398,
          "sha512": "93ebb6878a99a84d2b08d82cc441ee52c5a8762387334b5de9fa2ef7c89dd3e2e01ef49804b2145e01839f855a05fdb41a49e64f596b516d5c76f09e88cbaf1e",
          "sha256": "323c01ea42ab056ae55a0d3dc31be32f0deb8ac27e5c0ea47af1ad5dae1fe5da",
          "sha1": "1d24f0368f4119cfb328c15565ea6aef8da57ec4",
          "md5": "69eecc71d0ef29a79000b3f0916dec64"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bravepipeproject",
          "module": "timeago-parser",
          "version": {
            "requires": "v0.24.8-2.3.3-test5"
          }
        },
        {
          "group": "com.github.TeamNewPipe",
          "module": "nanojson",
          "version": {
            "requires": "e9d656ddb49a412a5a0a5d5ef20ca7ef09549996"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.31.1"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino-engine",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.github.evermind-zz",
          "module": "hlsdownloader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "4.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "extractor-v0.24.8-2.3.3-test5.jar",
          "url": "extractor-v0.24.8-2.3.3-test5.jar",
          "size": 972398,
          "sha512": "93ebb6878a99a84d2b08d82cc441ee52c5a8762387334b5de9fa2ef7c89dd3e2e01ef49804b2145e01839f855a05fdb41a49e64f596b516d5c76f09e88cbaf1e",
          "sha256": "323c01ea42ab056ae55a0d3dc31be32f0deb8ac27e5c0ea47af1ad5dae1fe5da",
          "sha1": "1d24f0368f4119cfb328c15565ea6aef8da57ec4",
          "md5": "69eecc71d0ef29a79000b3f0916dec64"
        }
      ]
    }
  ]
}
