{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bravepipeproject",
    "module": "timeago-generator",
    "version": "v0.24.8-2.3.3-test4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "timeago-generator-v0.24.8-2.3.3-test4.jar",
          "url": "timeago-generator-v0.24.8-2.3.3-test4.jar",
          "size": 13140,
          "sha512": "e235511d409bc400a52cdbc26e925d6e4701cfe6cb58b0e2b48719037ac88d62b39f4c8f4c8da20cc4de360928a4bbf755ac6dfe4da816854222571ad6e70161",
          "sha256": "4561250e688a867142e1d92600de2ca42f5e21f6e4068fbf9e66a3635edc8fb9",
          "sha1": "46d0bcc8d4acb4eadabde5a5f4c0d8b8b3ee967b",
          "md5": "13babe84849ece417f3d1e7fc3d45201"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.TeamNewPipe",
          "module": "nanojson",
          "version": {
            "requires": "e9d656ddb49a412a5a0a5d5ef20ca7ef09549996"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.github.bravepipeproject",
          "module": "timeago-parser",
          "version": {
            "requires": "v0.24.8-2.3.3-test4"
          }
        }
      ],
      "files": [
        {
          "name": "timeago-generator-v0.24.8-2.3.3-test4.jar",
          "url": "timeago-generator-v0.24.8-2.3.3-test4.jar",
          "size": 13140,
          "sha512": "e235511d409bc400a52cdbc26e925d6e4701cfe6cb58b0e2b48719037ac88d62b39f4c8f4c8da20cc4de360928a4bbf755ac6dfe4da816854222571ad6e70161",
          "sha256": "4561250e688a867142e1d92600de2ca42f5e21f6e4068fbf9e66a3635edc8fb9",
          "sha1": "46d0bcc8d4acb4eadabde5a5f4c0d8b8b3ee967b",
          "md5": "13babe84849ece417f3d1e7fc3d45201"
        }
      ]
    }
  ]
}
