{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bravepipeproject",
    "module": "extractor",
    "version": "v0.24.8-2.3.3-test3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "4.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "extractor-v0.24.8-2.3.3-test3.jar",
          "url": "extractor-v0.24.8-2.3.3-test3.jar",
          "size": 972398,
          "sha512": "42c96d4a481a1ca5310eb4159cc7fa757268bbe4ff34b2834ff0103ba6fac37f4ffd247d79b6a5c14adc06e41484980ad6cffa8a1fb74d9c6bcea5e2966734db",
          "sha256": "f81930e5ba6647c85ead33faaceae49adfafebf484987ccd9d49cb3e2e2c666a",
          "sha1": "6e471049ced49d8a3e6bade6a30efb1770164efa",
          "md5": "af1b94d09cdcde012c0790e57479cad3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bravepipeproject",
          "module": "timeago-parser",
          "version": {
            "requires": "v0.24.8-2.3.3-test3"
          }
        },
        {
          "group": "com.github.TeamNewPipe",
          "module": "nanojson",
          "version": {
            "requires": "e9d656ddb49a412a5a0a5d5ef20ca7ef09549996"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.31.1"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino-engine",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.github.evermind-zz",
          "module": "hlsdownloader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "4.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "extractor-v0.24.8-2.3.3-test3.jar",
          "url": "extractor-v0.24.8-2.3.3-test3.jar",
          "size": 972398,
          "sha512": "42c96d4a481a1ca5310eb4159cc7fa757268bbe4ff34b2834ff0103ba6fac37f4ffd247d79b6a5c14adc06e41484980ad6cffa8a1fb74d9c6bcea5e2966734db",
          "sha256": "f81930e5ba6647c85ead33faaceae49adfafebf484987ccd9d49cb3e2e2c666a",
          "sha1": "6e471049ced49d8a3e6bade6a30efb1770164efa",
          "md5": "af1b94d09cdcde012c0790e57479cad3"
        }
      ]
    }
  ]
}
